package project.model

/**
  * Some event generated by Nifi
 *
  * @param id - event id
  * @param value - some random value (UUID)
  * @param timestamp - time when event occurred
  */
case class Event(id: Long, value: String, timestamp: Long)
