package project.model

import com.sksamuel.avro4s.{AvroName, AvroNamespace}

/**
  * Some event generated by Nifi
 *
  * @param id - event id
  * @param value - some random value (UUID)
  * @param timestamp - time when event occurred
  */
@AvroName("event")
@AvroNamespace("project")
case class Event(id: Long, value: String, timestamp: Long)
