version: '3'
services:
  nginx:
    image: nginx:1.17
    hostname: finagle-nginx
    container_name: finagle-nginx
    depends_on:
      - server-1
      - server-2
      - client-1
      - client-2
    ports:
    - 8081:8081
    - 54321:54321
    volumes:
    - './nginx.conf:/etc/nginx/nginx.conf'
  server-1:
    image: finagle-rpc:0.1
    command: server
    hostname: server-1
    container_name: server-1
    environment:
      LISTENING_PORT: 12000
  server-2:
    image: finagle-rpc:0.1
    hostname: server-2
    container_name: server-2
    command: server
    environment:
      LISTENING_PORT: 12001
  client-1:
    image: finagle-rpc:0.1
    command: client
    hostname: client-1
    container_name: client-1
    environment:
      HTTP_LISTENING_PORT: 8001
      SERVER_HOST: finagle-nginx:54321
  client-2:
    image: finagle-rpc:0.1
    command: client
    hostname: client-2
    container_name: client-2
    environment:
      HTTP_LISTENING_PORT: 8002
      SERVER_HOST: finagle-nginx:54321