version: '3'
services:
  rabbitmq1:
    image: rabbitmq:3.7.17-management
    hostname: rabbitmq1
    container_name: rabbitmq1
    ports:
      - 5671:5672
      - 25671:25672
      - 15671:15672
      - 4361:4369
    environment:
      RABBITMQ_ERLANG_COOKIE: "cluster"
  rabbitmq2:
    image: rabbitmq:3.7.17-management
    hostname: rabbitmq2
    container_name: rabbitmq2
    ports:
      - 5672:5672
      - 25672:25672
      - 15672:15672
      - 4362:4369
    environment:
      RABBITMQ_ERLANG_COOKIE: "cluster"
  rabbitmq3:
    image: rabbitmq:3.7.17-management
    hostname: rabbitmq3
    container_name: rabbitmq3
    ports:
      - 5673:5672
      - 25673:25672
      - 15673:15672
      - 4363:4369
    environment:
      RABBITMQ_ERLANG_COOKIE: "cluster"