version: '2'
services:
  leader:
    image: tarantool/tarantool:1.10.0
    hostname: leader
    container_name: leader
    ports:
      - '3301:3301'
    volumes:
        - ./LeaderReplica.lua:/opt/tarantool/app.lua
    command: ["tarantool", "/opt/tarantool/app.lua"]
  follower:
    image: tarantool/tarantool:1.10.0
    depends_on:
      - leader
    hostname: follower
    container_name: follower
    ports:
    - '3302:3301'
    volumes:
    - ./FollowerReplica.lua:/opt/tarantool/app.lua
    command: ["tarantool", "/opt/tarantool/app.lua"]
