version: '3'
services:
  nginx:
    image: nginx:1.17
    ports:
      - '54321:54321'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
  server:
    image: avro-calculator-rpc:latest
    expose:
      - '12345'
    command: java -jar /app/application.jar server 12345